language: python
install:
  - pip install pyyaml
  - pip install coveralls
python:
  - "2.7"
script:
  - python validate_exercices.py
  - coverage run --source=graph validate_exercices.py
after_success:
  - coveralls
